### PR TITLE
Trim entities and POI chunks

### PR DESCRIPTION
**Pull request by ghost**
I made a mistake with my PR #13 and I can't edit it, sorry. 😅
Here's a new one, still to fix issue #12.

Note to myself : Deleting a fork before the PR is finished isn't a good idea, because you can't edit it again.

### CODE REVIEW

**Comment by ghost** [comment]
🤔 Up ? ^^

**Comment by Puremin0rez** [comment]
I apologize for the late reply, I have been very busy with work. 

I will be releasing a new version of WorldBorder for 1.19 sometime within the next few weeks, and I will review this PR and perform thorough testing before then. If the review goes well and all functionality works as expected, I hope to get this PR merged in for the upcoming release.

**Comment by Puremin0rez** [comment]
I have performed hours of testing across multiple different worlds of varying sizes and your PR has successfully passed all of my tests. I have merged your changes into the master branch and they will be available to everyone in the next release.

Thank you once again for your high quality contribution, it's greatly appreciated!

**Comment by ghost** [comment]
Hello,
Great, congratulations ! Thank you very much for your tests, I havn't done so many. I'm glad that my code works so well, and brings something to this project.
Have a nice day ! ^^

**Pull request merged**
